app:
  build: ./docker/app
  container_name: pi-app
  volumes:
    - .:/app
rtorrent:
  build: ./docker/rtorrent
  container_name: pi-rtorrent
  volumes:
    - ~/test/rtorrent:/downloads
  ports:
    - "49160:49160/udp"
    - "49161:49161"